const SCREEN_NAME = {
  HOME_SCREEN: 'HOME_SCREEN',
  CHAT_SCREEN: 'CHAT_SCREEN',
  MEDIA_SCREEN: 'MEDIA_SCREEN',
  CHAT_ROOM_SCREEN: 'CHAT_ROOM_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  SET_AVA_SCREEN: 'SET_AVA_SCREEN',
};
export {SCREEN_NAME};
